### PR TITLE
redesign wallet

### PR DESCRIPTION
**Pull request by chovy**
add sidebar

### CODE REVIEW

**Comment by jmank88** [comment]
Why is `package-lock.json` thrashing so much? Shouldn't we prefer exact versions in the lock? Rather than ranges?

**Comment by chovy** [comment]
@jmank88 my guess is npm 6.1.x changed the handling of package-lock.json. I didn't touch it manually.

**Comment by chovy** [comment]
I was going to lighten up the font a bit. I will do that.

Not sure what page is missing, I will look into it.

I will make the sidenav have an active menu item.

Can you get me an SVG wallet icon?

Home can probably go away. The hamburger button is really just to open the menu on mobile. Since there is no hover to open.

You don't have to click to open the menu on desktop, only on mobile. And you don't even have to open the menu, the icons are always visibible so you can just tap that on mobile.

**Comment by treeder** [comment]
The menu is closed for me on desktop.

**Comment by chovy** [comment]
You still see the icons is what I mean. Those are still clickable to take you to the page.

**Comment by chovy** [comment]
@treeder I added active state to the sidebar nav based on current page.

**Pull request merged**
